### ISSUE TITLE
Styles conflicts

### ISSUE THREAD

**Issue by PapsOu** [bluec0re/atom-rst-preview-docutils#6]
When displaying a rst preview pane, the embedded style conflicts with atom's theme.

Is there any way to encapsulate the rendered preview ? (a kind of iframe for example ?)

The use case : the following rule (that is embedded in the preview inline style) conflicts with atom tree view folder names : 
```css
 div.footer, div.header {
  clear: both;
  font-size: smaller }
```
